camera: do not use GNU old-style field designators
Avoiding the use of GNU extensions improves portability

Fixes the following:
error: use of GNU old-style field designator extension

Change-Id: Ic1bf7e44b3bf0c9b30c8c950b02ad71452a0bd8f
Signed-off-by: Alvin Francis <nivlafx@gmail.com>

# Conflicts:
#	camera/CameraHal_Module.cpp